### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by meme** [meme/fair-chair#1]
Not too difficult:
- [ ] Click to edit (in the listing menu)
- [ ] Code style formatting
- [ ] Remove vendored CSS and JS
- [ ] Testing suite

Long-term:
- [ ] Break everything into proper components (apparently this is broken?)
- [ ] Auto-complete (in the listing entry)

**Comment by meme** [comment]
Also, I honestly think it would be a good idea to just re-write this in React-- while we have the chance.
